_BASE_: "Base-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone"
  RESNETS:
    DEPTH: 101
  BiFPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 160
    NORM: "SyncBN"
  CONDINST:
    MASK_BRANCH:
      SEMANTIC_LOSS_ON: True
DATASETS:
  TRAIN: ("objects365_train",)
SOLVER:
  STEPS: (400000, 550000)
  MAX_ITER: 650000
OUTPUT_DIR: "output/condinst_MS_R_101_3x_bifpn_sem"
TEST:
  EVAL_PERIOD: 0
