_BASE_: "Base-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone"
  RESNETS:
    DEPTH: 50
  BiFPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 160
    NORM: "SyncBN"
  CONDINST:
    MASK_BRANCH:
      SEMANTIC_LOSS_ON: True
SOLVER:
  STEPS: (280000, 350000)
  MAX_ITER: 450000

OUTPUT_DIR: "output/condinst_MS_R_50_3x_bifpn_sem"
DATASETS:
  TRAIN: ("objects365_train",)
TEST:
  EVAL_PERIOD: 0
